####################################
# Hugo Site Configuration
####################################

baseURL = "https://fragda.hu/"
languageCode = "en-us"
title = "Fragda Official"
theme = "ananke"

####################################
# Site Parameters (Uncomment if needed)
####################################

# [params]
#   site_logo = "/images/fragda-logo.png"

[params]
  assetsDir = "static"  # Ensure Hugo knows where static files are
  site_logo = "/images/fragda-logo.png"  # Uncomment if needed

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  
####################################
# Navigation Menu
####################################

[[menu.main]]
  identifier = "releases"
  name = "Releases"
  url = "/releases/"
  weight = 1

[[menu.main]]
  identifier = "bio"
  name = "Bio"
  url = "/bio/"
  weight = 2

[[menu.main]]
  identifier = "concerts"
  name = "Concerts"
  url = "/concerts/"
  weight = 3

[[menu.main]]
  identifier = "shop"
  name = "Shop"
  url = "/shop/"
  weight = 4

[[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "/contact/"
  weight = 5
