[build]
  command = "hugo --gc --minify"
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.143.1"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  HUGO_BUILD_DRAFTS = "true"

[build.processing]
  skip_processing = false
  ignore = false  # Ensures all files are included

[[redirects]]
  from = "/"
  to = "/admin/"
  status = 302
  force = true
  query = { invite_token = ":invite_token" }

[functions]
  directory = "functions"

